### ISSUE TITLE
[General] data center machines unusable

### ISSUE THREAD

**Issue by vmx** [protocol/netops-guild#66]
### What do you need?

I can't connect to most of the worker-gpu-* machines anymore. I was able to connect to worker-gpu-5, but that machine seems to have DNS/networking issues. The issue was confirmed by @cryptonemo.
 => They are not usable and I'm blocked as I can't do my work on those machines.
  
### Why do you need it?

Please have a look and make sure that I can connect to those machines and that they don't have networking issues.
  
### Who is the DRI?

@vmx and @cryptonemo

### Team and command structure

FilCrypto

### Estimated monthly cost

N/A
  
### What else do we need to know?

That's all.

**Comment by vmx** [comment]
Update, I also cannot connect to `miner-2` or `worker-cpu-2-2`. Though I can connect to `worker-cpu-2-1`. This seems to be a bigger data center issue.

**Comment by vmx** [comment]
I should also note that 24h ago things still worked as expected.

**Comment by vmx** [comment]
I still can't ssh to e.g. `worker-gpu-6`, but `worker-gpu-5` doesn't have to seem networking issues anymore.

**Comment by ognots** [comment]
miner-2 should work now, I just rebooted it. it was wedged.
I was able to connect to the following machines and validate your user exists
* worker-cpu-2-1
* worker-cpu-2-2
* worker-gpu-6
* worker-gpu-5
Can you paste your SSH config?

**Comment by vmx** [comment]
Thanks a lot!

> * worker-cpu-2-1
> * worker-cpu-2-2
> * worker-gpu-6
> * worker-gpu-5

I can now ssh to those above. Though I cannot ssh to:

 - miner-2
 - worker-gpu-3
 - worker-gpu-4
 - worker-gpu-7
 - worker-gpu-8 (though that might not be in service any more, I haven't tried in a long time)

**Comment by vmx** [comment]
The networking still isn't good. E.g. on `woker-gpu-6` I need several retries to pull from GitHub. The error is something like:

```
fatal: unable to access 'https://github.com/filecoin-project/rust-fil-proofs/': Failed to connect to github.com port 443: No route to host
```

**Comment by vmx** [comment]
`worker-cpu-2-2` has the same networking issues.

**Comment by vmx** [comment]
Any news? The `worker-gpu-6` still has those networking issues.
